services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # RabbitMQ management interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  
  flask_server:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    container_name: flask_server
    environment:
      RABBITMQ_SERVER: rabbitmq
      RESULT_QUEUE: result_queue
    ports:
      - "5000:5000"


  compression_consumer:
    build:
      context: ../
      dockerfile: docker/Dockerfile.consumer
    container_name: compression_consumer
    environment:
      RABBITMQ_SERVER: rabbitmq
    command: ["python", "consumers/compression_consumer.py"]
    depends_on:
      - rabbitmq

