FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the dependencies
COPY src/consumer/requirements.txt /app/requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy all the consumer code
COPY src/consumer /app

# Create necessary directories for volumes
RUN mkdir -p /app/uploads /app/downloads

# Default command to run the consumer
CMD ["python", "main.py"]
