version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port pour AMQP
      - "15672:15672"  # Interface de gestion
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  flask_server:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    container_name: flask_server
    environment:
      RABBITMQ_SERVER: rabbitmq
      RESULT_QUEUE: result_queue
    volumes:
      - ./src/server/uploads:/app/uploads
      - ./src/server/downloads:/app/downloads
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  compression_consumer:
    build:
      context: ../
      dockerfile: docker/Dockerfile.consumer
    container_name: compression_consumer
    environment:
      RABBITMQ_SERVER: rabbitmq
      TASK_QUEUE: image_tasks
      RESULT_QUEUE: result_queue
    volumes:
      - ./src/server/uploads:/app/uploads
      - ./src/server/downloads:/app/downloads
    depends_on:
      - rabbitmq
