FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY src/consumers/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the consumer code
COPY src/consumers/compressor /app/

# Set environment variables
ENV UPLOAD_FOLDER=/app/uploads
ENV DOWNLOAD_FOLDER=/app/downloads

# Run the consumer
CMD ["python", "main.py"]
