FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les dépendances
COPY src/consumer/requirements.txt /app/requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code du consumer
COPY src/consumer /app

# Créer les dossiers nécessaires pour les volumes
RUN mkdir -p /app/uploads /app/downloads

# Commande par défaut pour lancer le consumer
CMD ["python", "main.py"]
